### ISSUE TITLE
[Q] How to do a CRC8

### ISSUE THREAD

**Issue by Sineos** [magiclen/node-crc#13]
I have following information:
![image](https://user-images.githubusercontent.com/4459312/216773247-960366ad-0757-40c1-a0ea-fb3d65f3b253.png)

and would like to calculate crc8 but somehow fail to get it working:

```
const result = crc.crc8(
    0x00, // polyLow
    0x31, // polyHigh
    8,
    0xFF, // initLow
    0xFF, // initHigh
    0x00, // XORlow
    0x00, // XORhigh
    false, // reflect
    Buffer.from([0xBE, 0xEF])
).toString('hex'));
```

Any pointer to where I'm wrong is appreciated. Thanks in advance.

**Comment by magiclen** [comment]
Modify `polyLow` to `0x31` and `polyHigh` to `0x00`, and you can get the correct result.

**Comment by Sineos** [comment]
Thank you very much for your help. Unfortunately, I still seem to hit a road block.

I'm using your module in node-red and:
`const result = nodeCrc.crc8(Buffer.from([0xBE, 0xEF])).toString('hex')`
works and returns `1A`. 

Using
```
const result = nodeCrc.crc8(
    0x31, // polyLow
    0x00, // polyHigh
    8,
    0xFF, // initLow
    0xFF, // initHigh
    0x00, // XORlow
    0x00, // XORhigh
    false, // reflect
    Buffer.from([0xBE, 0xEF])
).toString('hex')
```
does not work and throws `TypeError: failed to downcast any to Buffer`
Since the first example is working, I concluded that the error is due to me messing up the usage, i.e. setting the wrong parameters.

Using:
* Linux 5.15.84-v7+ arm LE
* Node-RED version: v3.0.2
* Node.js  version: v18.14.0
* NPM  version: v9.3.1

**Comment by magiclen** [comment]
Use the `crc` function, not `crc8`.

**Comment by magiclen** [comment]
See: https://github.com/magiclen/node-crc/blob/master/lib/lib.d.ts

**Comment by Sineos** [comment]
D'oh! Now that you put me on the right track, it is quite obvious. Thanks!
